### ISSUE TITLE
PlacementRefinements

### ISSUE THREAD

**Issue by jesterstud** [TwoClunkers/YesEat#24]
- [x] Create Basic Subjects (MVP)
- [x] Utilize Subjects in Object Creation
- [x] Debug Location Subject Passing
- [x] Delete Utility

**Comment by RossMcConeghy** [comment]
I added dummy subjects Plinkett and Location to the MasterSubjectList just to get the location discovery and movement debugged.

**Comment by jesterstud** [comment]
Yay
