### ISSUE TITLE
Clicking an object that is within a location sometimes selects the location and the object

### ISSUE THREAD

**Issue by RossMcConeghy** [TwoClunkers/YesEat#32]

**Comment by RossMcConeghy** [comment]
I have yet to reproduce this, it was happening during some testing but may have been a result of not fully initializing some test objects.

**Comment by RossMcConeghy** [comment]
I built the project to an EXE and was getting this quite a bit where clicking a mob in a location highlighted the location and the mob

**Comment by jesterstud** [comment]
I did find a hole where it was possible for two selection items. So hopefully this is taken care of.
